openapi: 3.0.0
info:
  title: ShulNET
  description: Sets of services for synagogue operations, to be used with front end or for integration.
  version: 0.1.1
servers:
  - url: http://localhost:6868
    description: Dev testing server.
paths:
  /members:
    get:
      summary: Returns a list of members.
      description: Returns a JSON array of members.
      responses:
        '200':    # status code
          description: A JSON array of members and data.
          content:
            application/json:
              schema: 
                type: array
                first_name: 
                  type: string
                last_name:
                  type: string
                middle_name:
                  type: string
                address_line_1:
                  type: string
                address_line_2:
                  type: string
                city:
                  type: string
                state:
                  type: string
                zip:
                  type: string
                country:
                  type: string
                phone:
                  type: string
                fax: